### ISSUE TITLE
Improper parsing of memo and payee

### ISSUE THREAD

**Issue by paxperscientiam** [egh/ledger-autosync#28]
Hello!

In the QFX format, I believe `<name>` corresponds to "payee".

Here is an example real world transaction:
````xml
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20170529235959<TRNAMT>-000000003.38<FITID>0529170148 000000003.38WG00Debit Card 542800<NAME>WILLISTON LIQUIDATI WILLISTON VT<MEMO>Debit Card W/D: Debit Card</STMTTRN>
````

ledger-autosync produces this:
````
 166 │ 2017/05/29 WILLISTON LIQUIDATI WILLISTON VT Debit Card W/D: Debit Card
 167 │     ; ofxid: 11809.0000751001392362.0529170148_000000003.38WG00Debit_Card______542800
 168 │     Northeast Credit Union                -$3.38
 169 │     Expenses:Misc                                           $3.38
````

Now, it seems to me that ledger-autosync ought to end up with 'WILLISTON LIQUIDATI WILLISTON VT' as the payee as opposed to  'WILLISTON LIQUIDATI WILLISTON VT Debit Card W/D: Debit Card'.

What do you think @egh ?

**Comment by egh** [comment]
The code for this is a little fragile. I've done what I could given the sampling of OFX files I had. They all seem to use `name` and `memo` differently. The code is here: https://github.com/egh/ledger-autosync/blob/master/ledgerautosync/converter.py#L219

See http://help.infinitekind.com/discussions/suggestions/1291-support-brain-damaged-ofx-usage-of-name-and-memo

That said, I'd be willing to consider changing the behavior, but it's hard to know what to do. It would be possible to have an option, but generally I'd prefer less options rather than more. That `memo` field seems really useless, though.

**Comment by paxperscientiam** [comment]
One thought that came to mind recently was the possibility of employing optional directives.

While the default behavior would be to assume proper implementation of the OFX standard with whatever best guess magic you've already employed, directives could be employed on a per institution basis.

Beyond that, I haven't quite fleshed the idea out. Unfortunately, this sort of bandaid is needed until the financial sector gets on board with OFX.

**Comment by egh** [comment]
Some sort of configuration system could certainly help to sort this out.

**Comment by paxperscientiam** [comment]
I noticed that, for one of my banks, QFX and OFX files contain some information not found in the other. Like, the institution is denoted in the OFX file but not the QFX. Silly.

~~With regard to this, could ledger-autosync -- instead of dying -- prompt for a custom institution name? Or, better yet, make a suggestion from list of institutions from ledger files?~~

Going to open a new issue for the above.

**Comment by egh** [comment]
In https://github.com/egh/ledger-autosync/commit/b41044baaaaa7c8315ff99335d78b5867a21b3b8 I have allowed setting a custom `payee-format` on the command line.
