### ISSUE TITLE
Prompt from list of known accounts?

### ISSUE THREAD

**Issue by paxperscientiam** [egh/ledger-autosync#29]
Shalom

Could ledger-autosync -- instead of dying -- prompt for a custom institution name? Or, better yet, make a suggestion from list of institutions from ledger files?

It seems that ledger-autosync follows includes -- is that accurate?

This should be implemented as an option. That is, if the end-user triggers the missing institution exception, they could then choose to execute ledger-autosync with this option turned on.

What do you think?

**Comment by egh** [comment]
You can specify the name using `-a Assets:Bank` but I admit that is not the best interface. However I have not added any interactive behavior and I believe that would complicate the ledger-autosync user interface to some extent. Another option would be allowing the `ofxclient.ini` file to specify the account name when importing from an ofx file (rather than using the ofx protocol.
